eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  common:
    redis:
      host: localhost
      port: 6379

    auth:
      service:
          url: http://auth-service:8080
