eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  redis:
    host: localhost
    port: 6379

cache:
    type: redis
  instance:
    hostname: localhost
  
    
