eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  common:
    redisHost: localhost
    redisPort: 6379
    authServiceUrl: http://auth-service:8080
