jwt:
  private-key-path: classpath:keys/private-key.pem
  public-key-path: classpath:keys/public-key.pem
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
   hibernate:
   ddl-auto: update
   show-sql: true
   
server:
  port: 8081
  
