spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
        - id: order-service
          uri: lb://order-service
          predicates:
          - Path=/order/**
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/user/**

server:
  port: 8989
