spring:
  cloud:
    gateway:
      routes:
        - id: os
          uri: lb://order-service
          predicates:
          - Path=/order/**
        - id: us
          uri: lb://user-service
          predicates:
            - Path=/user/**

server:
  port: 8989
