spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/order/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/user/**
        
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**

server:
  port: 8989
